#app_file:
#  resource: '@AcmeBundle/Resources/config/routing.yaml'

app_annotations:
  resource: '../src/Controller/'
  type: annotation
  prefix:
    en: '' # don't prefix URLs for English, the default locale
    nl: '/nl'

#app_directory:
#  resource: '../legacy/routing/'
#  type: directory

#app_static_routed_path:
  #path: /lucky/{product_id}
  #controller: App\Controller\LuckyController::fake